site_name: DXNN Streamer (DX-STREAM) User Manual
use_directory_urls: false
docs_dir: source # markdown 원문 폴더
site_dir: docs # html로 변환된 폴더
theme: 
  name : material
  language: en
  font:
    text: Noto Sans Display
    #text: Noto Serif
    #code: Noto Sans 
    code: Roboto Mono 
  logo: ./img/deepx.png
  favicon: ./img/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
     - toc.integrate
     - content.code.annotate
     - navigation.tabs
     - navigation.tabs.sticky
     - content.tabs.link
     - content.code.copy
site_url: 'https://developer.deepx.ai/'
nav:
  - DXNN SDK Overview: docs/01_DXNN_Streamer_Overview.md
  - DX-STREAM Installation: docs/02_DX-STREAM_Installation.md
  - Elements:
      - DxPreprocess: docs/Elements/03_01_DxPreprocess.md      
      - DxInfer: docs/Elements/03_02_DxInfer.md
      - DxPostprocess: docs/Elements/03_03_DxPostprocess.md
      - DxTracker: docs/Elements/03_04_DxTracker.md
      - DxOsd: docs/Elements/03_05_DxOsd.md
      - DxGather: docs/Elements/03_06_DxGather.md
      - DxInputSelector: docs/Elements/03_07_DxInputSelector.md
      - DxOutputSelector: docs/Elements/03_08_DxOutputSelector.md
      - DxRate: docs/Elements/03_09_DxRate.md
      - DxMsgConv: docs/Elements/03_10_DxMsgConv.md
      - DxMsgBroker: docs/Elements/03_11_DxMsgBroker.md
  - Writing Your Own Application: docs/04_Writing_Your_Own_Application.md
  - Pipeline Example:
      - Single Stream Pipeline: docs/Pipeline_Example/05_01_Single-Stream.md
      - Multi Stream Pipeline: docs/Pipeline_Example/05_02_Multi-Stream.md      
      - Secondary Inference Pipeline: docs/Pipeline_Example/05_03_Secondary-Inference.md
      - MsgBroker Pipeline: docs/Pipeline_Example/05_04_MsgBroker.md
  - Troubleshooting and FAQ: docs/06_Troubleshooting_and_FAQ.md
  - Appendix:
      - Build on OrangePi5Plus: docs/Appendix_Build_on_OrangePi5Plus.md
      - Performance Evaluation With GsgShark: docs/Appendix_Performance_Evaluation_with_GstShark.md
  - Change Log: docs/Appendix_Change_Log.md

plugins:
  - search
  - with-pdf:
      author: DEEPX.ai
      copyright: ⓒ Copyright 2025 DEEPX All Rights Reserved.
      #
      #cover: false
      cover_title: DXNN Streamer (DX-STREAM) User Manual
      cover_subtitle: v2.1.0
      cover_logo: img/deepx.png
      custom_template_path: docs/stylesheets
      #back_cover: true
      #
      #toc_title: TOC TITLE TEXT
      #heading_shift: false
      #toc_level: 3
      #ordered_chapter_level: 2
      #excludes_children:
      #    - 'release-notes/:upgrading'
      #    - 'release-notes/:changelog'
      #
      #exclude_pages:
      #    - 'bugs/'
      #    - 'appendix/contribute/'
      #convert_iframe:
      #    - src: IFRAME SRC
      #      img: POSTER IMAGE URL
      #      text: ALTERNATE TEXT
      #    - src: ...
      #two_columns_level: 3
      #
      #render_js: true
      #headless_chrome_path: headless-chromium
      #
      output_path: ../DEEPX_DX-STREAM_UM_v2.1.0.pdf
      #enabled_if_env: ENABLE_PDF_EXPORT
      #
      #debug_html: true
      #show_anchors: true
      #verbose: true
#  - mkdocs-video
extra:
  homepage: https://developer.deepx.ai
#  version:
#    provider: mike
#    default: stable
  generator: false
  social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/deepx-ai
     - icon: fontawesome/brands/linkedin
       link: https://www.linkedin.com/company/deepx-corporation/
#  alternate:
#    - name: English
#      link: /en/    
#      lang: en
#    - name: Korean
#      link: /kr/
#      lang: kr
extra_css: 
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - def_list
  - toc:
        permalink: "true"
        baselevel: 1
        separator: ">_"
        toc_depth: 3
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: ⓒ Copyright 2025 <a href="http://deepx.ai">DEEPX</a>. All Rights Reserved.
